# Publish the PDF
name: Publish

# Controls when the workflow will run - when a tag is created
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex thesis
            biber thesis
            makeglossaries thesis
            pdflatex thesis
            pdflatex thesis

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: thesis.pdf
          tag: ${{ github.ref }}
          asset_name: thesis-$tag.pdf
